

export const stuffAndFood = [
    'Pain et jambon Δ4, sac en tissu déchiré, chaussette remplie de cailloux',
    'Biscuits secs et noix Δ8, vieille besace, couverture, corde Δ10, chapeau de pèlerin',
    'Pot de soupe aux escargots Δ6, bœuf de trait Δ8, tapis roulé, 2 sacs Δ4, pied-de-biche',
    'Navets bouillis au beurre Δ6, sacoches vides Δ6, sac de couchage, 2 pièges à ours',
    'Saucisse au foie et à la tomate Δ4, torches Δ6, outils de voleur de cadavres, pitons Δ6',
    'Fèves et viande séchée Δ8, outils de calligraphe Δ8, symbole sacré Δ6, lanterne et huile Δ8',
    'Lapins fraîchement pris Δ4, pièges, sac de couchage, bougies Δ4, jeu de dés',
    'Pommes séchées Δ8, chien de berger Δ6, vieux havresac Δ6, tente Δ10, torches Δ6',
    'Pain de campagne et poisson salé Δ8, grand filet, lettre de marque, menottes',
    'Farine de haricots et mouton séché Δ4, vieux canasson Δ6, manteau de pluie, torches Δ6',
    'Terrine de sanglier et bière Δ6, eau bénite Δ6, outils d’alchimiste Δ8, bougies Δ4',
    'Chou farci au canard Δ6, sac de charbon, canne à pêche, jeu de cartes',
    'Pain frais et fruits Δ6, lampe, huile Δ4, carte des environs, pelle, échelle de corde',
    'Poule dans une cage Δ6, sac de couchage, torches Δ6, ustensiles de cuisine, jeu de tarot',
    'Boudin noir et vin bouchonné Δ6, outils de serrurier Δ8, havresac Δ8, lanterne et huile Δ8',
    'Gâteaux au miel et au citron Δ4, vêtements de voyage raffinés, cheval de guerre Δ10, ingrédients magiques Δ6',
    'Tourte à la loutre Δ6, outils de courtisan Δ8, cape de qualité, oiseau chanteur en cage',
    'Gâteaux de poisson et vin sec Δ6, sac de café Δ8, outils d’arnaqueur, corde Δ10, dés pipés',
    'Repas en conserve Δ8, outils de calligraphe Δ8, chapeau de magicien, lorgnette, ingrédients magiques Δ8',
    'Fromage poivré et cidre Δ4, étalon de race Δ10, outils de cartographe Δ8, torches Δ6'
]

export const wealthAndValuables = [
    'Un morceau de cordelette et une dent',
    'Un sac de longs clous rouillés',
    'Des fourrures d’une valeur de cuivre Δ10',
    'Une poche pleine de sous de cuivre Δ6',
    'Une longueur de soie valant argent Δ10',
    'Des urnes funéraires valant argent Δ6',
    'Une pile de lettres codées et bourse de pièces d’argent Δ4',
    'Une bourse en cuir remplie de pièces d’argent Δ8',
    'Des livres religieux valant argent Δ12',
    'Une escarcelle de pièces argent Δ10',
    'Des bijoux volés valant argent Δ12',
    'Une jolie bourse de pièces d’électrum Δ6',
    'Des habits raffinés valant électrum Δ8',
    'Un lingot d’électrum Δ10',
    'Une aumônière en velours contenant des pièces d’électrum Δ10',
    'Une bague valant or Δ8',
    'Une ceinture porte-monnaie contenant des pièces d’or Δ6',
    'Un lingot de platine Δ4',
    'Une lourde statuette valant platine Δ6',
    'Un parchemin magique rare valant or Δ12',
]

export const handToHandWeapons = [
    'Matraque d4 ou fourche d6',
    'Dague ou poignard d4',
    'Fouet ou knout d4',
    'Hachette ou marteau d6',
    'Vouge ou anicroche d6*',
    'Épée courte ou scramasaxe d6',
    'Bâton de combat ou shillelagh d6',
    'Rapière ou sabre d’abordage d6',
    'Pique de brèche ou lance d6/d6*',
    'Pertuisane ou corsèque d8*',
    'Hache danoise ou fléau d8/d8*',
    'Épée longue ou cimeterre d8',
    'Sabre ou yatagan d8',
    'Pique ou bardiche d8*',
    'Bec de corbin ou masse d8*',
    'Épée bâtarde ou claymore d8/d8*',
    'Marteau de Lucerne ou plommée d10*',
    'Hache de Lochaber ou hallebarde d10*',
    'Morgenstern ou fléau d10',
    'Flamberge ou espadon d10*'
]

export const armors = [
    'Casque mal ajusté Δ4*',
    'Bocle ou bouclier de cuir',
    'Tunique en peau et coiffe de fourrure Δ4*',
    'Manteau de cuir Δ4 et bouclier rond',
    'Gambison ou cuir matelassé Δ4*',
    'Cuir bouilli Δ6',
    'Harnais en cuir Δ6',
    'Cuir clouté Δ6 avec bouclier',
    'Plastron Δ6',
    'Brigandine Δ8',
    'Broigne à écailles ou lorique Δ8',
    'Plastron avec casque Δ8 et bouclier',
    'Cotte de mailles avec heaume Δ8',
    'Mailles et cuir avec bouclier Δ8',
    'Haubert avec bouclier rond Δ8',
    'Plaque composite rouillée Δ10',
    'Plastron et chemise de mailles avec camail Δ10',
    'Armure de plaques lourde Δ10 et pavois',
    'Armure d’apparat Δ10 et bouclier normand',
    'Plate complète Δ10 et écu',
]

export const rangedWeapons = [
    'Galets polis d4 (sac Δ10)',
    'Couteaux de lancer d6 (ceinture Δ4)',
    'Fléchettes d6 (carquois Δ6)',
    'Fronde d4 (sac de pierres Δ10)',
    'Pistolet arbalète d6 (carquois Δ8)',
    'Pistolet de duel Δ6 (poudre et balles Δ4)',
    'Bolas d4',
    'Javelots d6 (carquois Δ4)',
    'Arc long d8 (carquois Δ8)',
    'Tromblon Δ8* (poudre et clous Δ4)',
    'Pistolet de cavalier Δ8 (poudre et balles Δ4)',
    'Arc de nomade d6 (carquois Δ8)',
    'Haches de lancer d6 (ceinture Δ4)',
    'Lourde lame de lancer d8',
    'Arbalète à répétition d8 (carquois Δ10)',
    'Grenades d10* (ceinture Δ4)',
    'Arbalète de siège d10 (carquois Δ8)',
    'Propulseur d8 (javelots Δ6)',
    'Arquebuse Δ8 (poudre et balles Δ8)',
    'Mousquet Δ10 (poudre et balles Δ6)',
]

export const magicTrinkets = [
    'Le porte-bonheur d’un être cher',
    'Bocal d’antidote universel Δ6',
    'Statuette de bronze primitive (Δ4 in.)',
    'Poignée de baies magiques (soins Δ4)',
    'Relique d’un demi-saint (Δ6 in.)',
    'Fiole de poison paralysant Δ6',
    'Sachet d’encens des Grands oracles Δ4',
    'Poignée de plumes d’hibours (Δ8 in.)',
    'Masse de flescargot (dégâts ou in. Δ6)',
    'Potion de métamorphose (durée Δ10)',
    'Poudre noirâtre Δ10 (à sniffer comme in.)',
    'Flacon d’élixir de la Croix (soins Δ8)',
    'Cape d’armure Δ10 (ou utilisée comme in.)',
    'Chaussettes de marche des nuées Δ8',
    'Têtes de singe réduites (Δ12 in.)',
    'Fez d’empathie Δ8 (ou comme in.)',
    'Pièces de la Cité des Ombres (Δ12 in.)',
    'Fléchettes infaillibles (dégâts Δ10)',
    'Boîte de grains de café ju-ju (Δ12 in.)',
    ' Baguette de coercition Δ10 (ou comme in.)',
]

export const legacy = [
    'Une malédiction ! Vous êtes par exemple un lycanthrope ou un passif-agressif.',
    'Un bouton de culotte lustré, transmis d’une génération à l’autre.',
    'La moitié d’une carte… au trésor, peut-être ? Dur à dire tant que vous n’avez pas l’autre moitié.',
    'La hache de bataille de grand-papi (d6). Elle est usée et mal équilibrée, mais toujours efficace.',
    'Une caisse de vin millésimé gardée pour une occasion spéciale. Elle vaut Δ8 argent.',
    'L’épée de maman (d8). Elle a un nom, une histoire et peut-être un pouvoir magique mineur.',
    'L’acte de propriété d’une mine, quelque part au fin fond des confins du pays',
    'Un titre de noblesse mineur (chevalier, baronnet, bey, patricienne, etc.) et guère plus',
    'Votre ancêtre a fabriqué cette flèche qui ne rate jamais sa cible (d8). Elle n’a jamais servi.',
    'Un héritage considérable (or Δ12) d’une lointaine tante. Mais il y a une condition à remplir.',
    'La formule d’un sort unique et puissant. Ça vaut très cher pour certaines personnes.',
    'Un titre de noblesse (raïs, vicomte, duchesse, khan, etc.) et un garde du corps (Δ10).',
    'Une énorme cafetière magique. Elle produit un nectar que vous pourrez faire payer cher.',
    'La clef de la tour d’un archimage et le mot de commande de… quelque chose.',
    'La faucheuse de fléaux (d12), une arme puissante destinée à sauver le monde. Supposément.',
    'Le véritable nom d’une princesse démone et un ensemble incomplet d’instructions pour l’utiliser.',
    'Une orchidée magique et parlante qui connaît le chemin vers un jardin merveilleux.',
    'Du sang divin, mais pas de pouvoirs magiques. Certains cultes vous portent un intérêt particulier.',
    'Une part dans une société de commerce planaire, et des dividendes annuels (platine Δ6).',
    'Le trône ! Enfin, vous êtes bien placé dans l’ordre de succession.',
]

export const faith = [
    'Je suis un humble et misérable serviteur du Pourvoyeur de Seigle et de Lait. (Δ4)',
    'Je porte les chaînes d’un prêtre au service de l’Impératrice des esclaves. (Δ6)',
    'Le Croupier du Destin me montre parfois sa main. (Δ4)',
    'J’ai copié tant de textes sacrés que je peux citer les saintes écritures toute la journée. (Δ4)',
    'En tant que Connétable de l’Ordre éternel, je dois toujours faire respecter les règles. (Δ6)',
    'J’ai avalé une relique et elle n’est jamais ressortie. (Δ4)',
    'Celle qui porte la Couronne d’or nous enseigne que la richesse est la vraie sainteté. (Δ6)',
    'Les frères de la Quête sans fin font le vœu de toujours découvrir la vérité. (Δ6)',
    'Je crois juste en Mère Nature, mec ! (Δ6)',
    'En tant que Sœur indigente de la Barbe pleureuse, je ne peux rien posséder. (Δ8)',
    'Je suis un Architecte du Réel, un export constructeur de machines merveilleuses. (Δ6)',
    'Le chemin d’un Pâtre de la Paix est ardu, surtout chez les aventuriers. (Δ10)',
    'Au crois chaos je Chaos chaos C H A 0 S (Δ8) chaos chaos',
    'Mon Église s’aventure dans les contrées sauvages pour faire avancer la Sainte civilisation. (Δ8)',
    'Le plan matériel n’est qu’illusion. Pécheurs, embrassez le Vide Vivace ! (Δ8)',
    'Tout est destiné à mourir, disent les Røis de l’Entrøpie. J’accepte mon rôle dans leur plan. (Δ8)',
    'Avez-vous douze heures pour parler de Notre Dame la Broyeuse d’Âmes ? (Δ8)',
    'Je suis un avatar du Voyageur. Je dois marcher encore et toujours. (Δ10)',
    'Je me suis aveuglé en échange de bénédictions de la Nuit Éternelle. (Δ10)',
    'Kolair le Rancunier parle à travers moi et tue par ma main. Repentez-vous ! (Δ12)',
]

export const monsterMotivations = [
    'Lancez deux fois et mélangez les résultats',
    'Chercher des alliés ou de l’aide',
    'Déménager ou s’échapper',
    'Tendre une embuscade ou faire un raid',
    'Fuir d’autres monstres',
    'Repousser les intrus',
    'Chercher des prisonniers',
    'Chercher du matériel ou chasser',
    'Explorer',
    'Se chamailler entre eux',
    'Se reposer ou monter le camp',
    'Chercher des biens pour commercer',
]

export const pnjMotivations = [
    'Dette et désespoir',
    'Histoire d’amour ou d’amitié',
    'Puissance et gloire',
    'Envie de voir du pays',
    'Besoin d’impressionner quelqu’un',
    'Vengeance',
    'Un serment solennel',
    'Échapper à la justice',
    'Une pulsion suicidaire',
    'Un sens du devoir ou de la destinée',
    'Payé par une tierce partie',
    'Une vision ou un dessein divin',
]

export const enemiesMoral = [
    'Désespérés : reçoivent et subissent doubles dégâts.',
    'Fuite : ils laissent du matériel derrière eux.',
    'Reddition : si les PJ refusent, leur Δ augmente.',
    'Retraite : ils se regroupent en bon ordre.',
    'Panique : ils agissent à l’encontre de leurs intérêts.',
    'Combat défensif : recherche de couvert, etc.',
    'La meilleure défense... ils prennent un risque pour gagner rapidement.',
    'Frénésie : doubles dégâts sur les PJ et leurs alliés.',
    'Feinte : ils battent en retraite pour tendre un piège.',
    'Opportunité : ils exploitent une faiblesse dans la stratégie des PJ.',
    'Coup de fouet : relancer les dés de vie des monstres.',
    'Soif de sang : désavantage pour attaquer les monstres.',
]

export const mercenarySkills = [
    'Porte-flambeau : nombre d’objets supplémentaires qu’il peut transporter (cumulatif).',
    'Lancier : dégâts supplémentaires sur sa première attaque.',
    'Éclaireur : distance explorée en avant du groupe (en kilomètres).',
    'Magicien errant : nombre de sorts (très mineurs) connus.',
    'Hobbit : s’il cuisine, nombre de personnages recevant l’avantage sur le jet de CON de leur nuit de repos (cf. page 28).',
    'Aumônier : nombre de personnes protégées contre le Mal / Chaos / autre(avantage pour résister à la magie).',
    'Elfe : nombre de fois qu’il donne l’avantage pour repérer un ennemi ou un passage secret.',
    'Garde du corps : points d’armure supplémentaires pour son client.',
    'Nain : nombre de fois où il donne l’avantage pour trouver un trésor ou un piège mécanique.',
    'Chirurgien : total des points de vie qu’il soigne après un combat.',
    'Voleur : nombre de gens qui ont l’avantage pour leur jet de discrétion.',
    'Barde : nombre d’encouragements musicaux par jour (avantage sur un jet de dé).',
]

export const dungeonExploration = [
    'Rencontre : prête à tendre une embuscade aux personnages.',
    'Ressource : lancez le Δ des sources d’éclairage et le Δ de moral des suivants.',
    'Rencontre : standard (décidez ou lancez le dé pour la réaction).',
    'Ressource : lancez le Δ des sources d’éclairage.',
    'Rencontre : pas consciente de la présence des PJ.',
    'Ressource : les personnages encombrés lancent leur Δ de nourriture.',
    'Rencontre : dans le pétrin (décidez comment).',
    'Ressource : lancez le Δ des sources d’éclairage et le Δ de moral des suivants.',
    'Rencontre : proche. Les PJ découvrent des indices de sa présence.',
    'Trouvaille : une ressource non gardée.',
    'Rencontre : morte (décidez comment).',
    'Trouvaille : un trésor non gardé.',
]

export const weather = [
    'Orage ou blizzard',
    'Pareil qu’hier, mais plus froid',
    'Pluie ou neige',
    'Du vent, températures plus froides que la normale',
    'Des averses et du vent',
    'Des averses, pas de vent',
    'Nuageux, pas de vent',
    'Sec et ensoleillé avec du vent',
    'Ensoleillé, plus chaud que la normale',
    'Du vent, temps plus chaud que la normale',
    'Pareil qu’hier, mais plus chaud',
    'Événement météorologique exceptionnel',
]

export const explorationOfTheWilderness = [
    'Rencontre : prête à tendre une embuscade aux personnages.',
    'Ressource : jetez le Δ de météo et le Δ de moral des suivants.',
    'Rencontre : standard (décidez ou lancez un dé pour la réaction).',
    'Ressource : jetez un Δ d’équipement (un objet par personnage).',
    'Rencontre : pas consciente de la présence des PJ.',
    'Ressource : les personnages encombrés jettent leur Δ de nourriture.',
    'Rencontre : en danger (décidez comment).',
    'Ressource : un personnage lance un Δ d’équipement, un suivant lance son Δ de moral.',
    'Rencontre : proche. Les PJ découvrent des indices de sa présence.',
    'Trouvaille : une ressource non gardée.',
    'Rencontre : morte (décidez comment).',
    'Trouvaille : trésor non gardé.',
]

export const huntingAndGathering = [
    'Vous ne trouvez rien mais un monstre vous trouve.',
    'Viande fraîche Δ6.et quelque chose en train de la manger.',
    'Rien d’autre que de l’écorce d’arbre et des larves Δ4.',
    'Châtaignes ou noix Δ8.',
    'Écureuils ou pigeons Δ6.',
    'Escargots et pissenlits Δ8.',
    'Pommes et poires Δ6.',
    'Miel et racines Δ8.',
    'Poisson et aromates Δ6.',
    'Gibier de qualité Δ10.',
    'Champignons et baies délicieuses Δ8.',
    'Relancez deux fois, ignorez les 1.',
]

export const campEvents = [
    'Attaque. Les monstres de la région attaquent la ville ou le camp. Que veulent-ils ?',
    'Éclaireurs. Des monstres ou des troupes ennemies sont repérés dans la région. Sont-ils seulement de passage ?',
    'Espions. Un étranger est surpris en train d’espionner. Pour qui travaille-t-il ?',
    'Pénurie. La nourriture, l’eau ou une autre ressource vitale vient à manquer.',
    'Nouveaux venus. En route vers ailleurs ou ayant l’intention de rester ?',
    'Maladie. Probablement bénigne, mais la peste pourpre et la lycanthropie sont toujours un risque.',
    'Rumeurs. Qu’il s’agisse d’une nouvelle ou d\'une ancienne menace, tout le monde en parle.',
    'Au feu ! Quelque chose est détruit. Était-ce vraiment un accident ?',
    'Dura lex. Quelqu’un est arrêté, interrogé ou pendu.',
    'Approvisionnement. Une caravane ou un groupe de chasseurs rapporte des biens de grande valeur.',
    'Événement religieux. La cérémonie hebdomadaire ou un jour sacré qui n’a lieu qu’une fois par siècle.',
    'Luttes intestines. Des individus ou des factions s’en prennent les uns aux autres.',
]

export const fastTravel = [
    'Capturés. Vous vous en sortez in extremis avec un seul objet (de votre choix) dans votre inventaire.',
    'Embuscade coûteuse. Relancez vos DV pour connaître vos PV actuels.',
    'Poursuite épuisante. Jet de CON ou perte de d6 objets.',
    'Désorientés. Le voyage prend d4 jours supplémentaires, et vous n’avez plus de rations.',
    'Comme ci-dessus, mais vous avez fait une découverte : un lieu, une ressource, un danger...',
    'Rencontre non violente avec des monstres ou des gens du cru.',
    'Découverte, à condition d’en payer le prix (en matériel, trésor, PV, etc.).',
    'Des monstres tués et découverte d’un trésor.',
    'Combat contre des monstres, certains d’entre eux se sont enfuis. Jetez vos Δ de munitions et d’armure.',
    'Découverte de nourriture. Aucune ration n’est dépensée.',
    'Raccourci. Vous gagnez 1 jour de voyage.',
    'Vous avez fait une découverte (un danger, une ressource, une opportunité, etc.).',
]

export const catchUpTheGroup = [
    'Vous avez perdu toutes vos armes et votre équipement, sauf d6 objets de votre choix.',
    'Vous avez échappé de justesse à des monstres... qui sont sur le point de vous rattraper.',
    'Vous avez tué un monstre. Relancez vos DV pour connaître vos PV actuels.',
    'Un PNJ allié a été tué par des monstres. Vous savez par où ils se sont enfuis.',
    'Contact non violent avec un monstre ou une faction.',
    'Vous avez rencontré un monstre et en avez fait un allié.',
    'Vous êtes traqué par quelqu’un ou quelque chose. Il n’est pas loin.',
    'Vous avez trouvé un indice concernant un danger proche.',
    'Vous êtes tombé dans un trou et avez perdu une arme au hasard.',
    'Vous avez marché sur un piège. Lancez les Δ de tout votre équipement.',
    'Vous avez trouvé un cadavre et avez pris quelque chose d’intéressant.',
    'Relancez le Δ deux fois en ignorant ce résultat.',
]

export const complications = [
    'Attaque : des bandits, des monstres ou des rivaux. Ça va saigner !',
    'Effondrement financier : dépensez du platine*.',
    'Agitation : les habitants, employés, etc., sont en colère.',
    'Désastre : naturel ou magique.',
    'Gestion calamiteuse : dépensez de l’or*.',
    'Tentative d’assassinat : à résoudre en jeu.',
    'Inquiétudes commerciales : un partenaire s’enfuit, un concurrent devient agressif.',
    'Dépenses imprévues : dépensez de l’électrum*.',
    'Défection : un agent, un vassal ou un employé part relever d’autres défis.',
    'Faiblesse : un adversaire apprend quelque chose qu’il peut utiliser contre vous.',
    'Dépassement de budget : dépensez de l’argent*.',
    'Défi : un rival ou un adversaire vous fait des misères.',
]

// TODO :
// Accidents magiques (Δ du chaos) p. 31
// Conséquence du jet raté pour le travail p.36
// Conclusion (dé d’expédition) p. 37
// Faisons la fête ! (Δ de monnaie) p.37
// Domaine p.38